steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/931667784738/notificacao-mestrado', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/931667784738/notificacao-mestrado']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'notificacao-mestrado', '--image', 'gcr.io/931667784738/notificacao-mestrado', '--region', 'us-central1']
images:
- gcr.io/931667784738/notificacao-mestrado