steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - notificacao-mestrado-ufc
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python310
  - --entry-point=index